sig/coprocessor:
  - any: [ "sig/coprocessor/*","!sig/coprocessor/membership.json" ]

sig/engine:
  - any: [ "sig/engine/*","!sig/engine/membership.json" ]

sig/raft:
  - any: [ "sig/raft/*","!sig/raft/membership.json" ]

sig/scheduling:
  - any: [ "sig/scheduling/*","!sig/scheduling/membership.json" ]

sig/transaction:
  - any: [ "sig/transaction/*","!sig/transaction/membership.json" ]